name: Build Releases

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # TODO actually build the container

      - run: |
          echo "Finished building and pushing containers."
