name: Linters and Tests

on:
  workflow_call:

jobs:
  pre-commit:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "pip"

      - name: Run linter
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch

  security:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          cache: true
          version: latest

      - name: Run trivy configuration checks
        run: |
          trivy config . --config=.trivy.yaml --ignorefile=.trivyignore

      - name: Run trivy filesystem checks
        run: |
          trivy filesystem . --config=.trivy.yaml --ignorefile=.trivyignore --no-progress

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # NOTE: just leaving this here as an example
    #services:
    #  postgres:
    #    image: docker.io/library/postgres:17
    #    env:
    #      POSTGRES_PASSWORD: postgres
    #    # set health checks to wait until postgres has started
    #    options: >-
    #      --health-cmd pg_isready
    #      --health-interval 10s
    #      --health-timeout 5s
    #      --health-retries 5
    #    ports:
    #      - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "poetry"

      - name: Run python tests
        run: |
          poetry install --no-interaction
          poetry run pytest --cov=src --cov-report=term --cov-fail-under=50

      - name: Run container tests
        run: |
          docker build .
